baseURL = '/'
languageCode = 'en-us'
title = 'Cybersecurity Research Blog'
theme = 'hello-friend-ng'
[pagination]
  pagerSize = 10


[params]
  # Subtitle for home
  contentTypeName = "posts"
  showLanguageSelector = false
  enableSharingButtons = true
  images = [""]
  homeSubtitle = "Red Team, Malware Research & more"
  
  portrait = { path = "/images/logoTwitter.png", alt = "My Portrait", maxWidth = "auto" }

[[params.social]]
  name = "github"
  url = "https://github.com/8erg"
[[params.social]]
  name = "/images/logoTwitter.png"
  url = "https://malware-chronicles.beehiiv.com/"

[languages]
  [languages.en]
    title = "Cybesecurity Research Blog "
  [languages.en.params]
    owner = "8erg"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "8erg's Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
	      identifier = "Posts"
	      name = "Posts"
	      url = "/posts"
